# Generated by Django 2.2.6 on 2019-11-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='ddd_telefone',
            field=models.CharField(help_text='(Formato 99)', max_length=2, verbose_name='DDD'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(help_text='(Formato 99999-9999)', max_length=10, verbose_name='Telefone'),
        ),
    ]
