# Generated by Django 2.2.6 on 2019-10-20 05:49

from django.db import migrations, models
import produto.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20191019_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(default=None, null=True, upload_to=produto.models.subdiretorio_foto_produto, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
    ]
