# Generated by Django 2.2.6 on 2019-10-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20191020_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='qtd_estoque',
            field=models.IntegerField(help_text='Informe a quantidade atual', verbose_name='Estoque'),
        ),
    ]
